# Use the official Docker Hub Postgres image
FROM postgres:latest

# Set environment variables
ENV POSTGRES_USER pepper-app
ENV POSTGRES_PASSWORD pepper-app
ENV POSTGRES_DB pepper-app

# add sql files into container
ADD sql/tables.sql /data/tables.sql

# add init.sh script into container
COPY sh/init.sh /docker-entrypoint-initdb.d/init.sh

# Expose the PostgreSQL port
EXPOSE 5432
